# Generated by Django 5.2.4 on 2026-01-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='analysis_status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='calories_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='carbs_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredient_image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='protein_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
