# Generated by Django 6.0.1 on 2026-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='영화 제목')),
                ('release_year', models.IntegerField(verbose_name='개봉 년도')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='감독')),
                ('genre', models.CharField(choices=[('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('공포', '공포'), ('SF', 'SF'), ('로맨스', '로맨스'), ('스릴러', '스릴러'), ('애니메이션', '애니메이션'), ('판타지', '판타지'), ('다큐멘터리', '다큐멘터리')], max_length=50, verbose_name='장르')),
                ('actors', models.CharField(blank=True, max_length=500, verbose_name='주연배우')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='러닝타임(분)')),
                ('rating', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=3, verbose_name='별점')),
                ('review', models.TextField(blank=True, verbose_name='리뷰 내용')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터 이미지')),
                ('poster_url', models.URLField(blank=True, verbose_name='포스터 URL')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID')),
                ('is_tmdb', models.BooleanField(default=False, verbose_name='TMDB 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화들',
                'ordering': ['-created_at'],
            },
        ),
    ]
