# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_id_movieembedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieEmbedding',
        ),
    ]
