# Generated by Django 4.2.27 on 2026-01-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_delete_movieembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='movies.movie')),
            ],
        ),
    ]
