# Generated by Django 6.0 on 2025-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
